-- MySQL Script generated by MySQL Workbench
-- Wed 18 Jan 2017 04:12:48 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `accounts_id` INT NOT NULL AUTO_INCREMENT,
  `accounts_type` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`accounts_id`, `accounts_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medewerkers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medewerkers` (
  `medewerkers_id` INT NOT NULL AUTO_INCREMENT,
  `FK_accounts_id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  PRIMARY KEY (`medewerkers_id`, `FK_accounts_id`),
  INDEX `fk_Medewerker_Account1_idx` (`FK_accounts_id` ASC),
  CONSTRAINT `FK_medewerkers_accounts_id`
    FOREIGN KEY (`FK_accounts_id`)
    REFERENCES `mydb`.`accounts` (`accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adressen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adressen` (
  `adressen_id` INT NOT NULL AUTO_INCREMENT,
  `adresssen_type` INT NOT NULL,
  `FK_klanten_id` INT NOT NULL,
  `huisnummer` VARCHAR(45) NOT NULL,
  `huisnumer_toevoeging` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `land` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adressen_id`, `adresssen_type`, `FK_klanten_id`),
  INDEX `FK_klanten_id_idx` (`FK_klanten_id` ASC),
  CONSTRAINT `FK_adressen_klanten_id`
    FOREIGN KEY (`FK_klanten_id`)
    REFERENCES `mydb`.`klanten` (`klanten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`klanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klanten` (
  `klanten_id` INT NOT NULL AUTO_INCREMENT,
  `FK_accounts_id` INT NOT NULL,
  `FK_adressen_klant` INT NULL,
  `FK_adressen_type` INT NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `telefoonnummer` INT NULL,
  PRIMARY KEY (`klanten_id`, `FK_accounts_id`),
  INDEX `fk_Klant_Account1_idx` (`FK_accounts_id` ASC),
  INDEX `FK_adressen_klant_idx` (`FK_adressen_klant` ASC, `FK_adressen_type` ASC),
  CONSTRAINT `FK_klanten_accounts_id`
    FOREIGN KEY (`FK_accounts_id`)
    REFERENCES `mydb`.`accounts` (`accounts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_adressen_klant`
    FOREIGN KEY (`FK_adressen_klant` , `FK_adressen_type`)
    REFERENCES `mydb`.`adressen` (`adressen_id` , `adresssen_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producten` (
  `producten_id` INT NOT NULL AUTO_INCREMENT,
  `omschrijving` VARCHAR(45) NULL,
  `soort` VARCHAR(45) NULL,
  `prijs` DECIMAL NULL,
  `voorraad` INT NULL,
  PRIMARY KEY (`producten_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bestellingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bestellingen` (
  `bestellingen_id` INT NOT NULL AUTO_INCREMENT,
  `FK_klanten_id` INT NULL,
  `FK_adressen_bestelling` INT NULL,
  `FK_adressen_type` INT NULL,
  `aantal_artikelen` INT NULL,
  `totaalprijs` DECIMAL NULL,
  PRIMARY KEY (`bestellingen_id`, `FK_klanten_id`),
  INDEX `fk_Bestelling_Klant1_idx` (`FK_klanten_id` ASC),
  INDEX `FK_adressen_bestelling_idx` (`FK_adressen_bestelling` ASC, `FK_adressen_type` ASC, `FK_klanten_id` ASC),
  CONSTRAINT `FK_bestellingen_klanten_id`
    FOREIGN KEY (`FK_klanten_id`)
    REFERENCES `mydb`.`klanten` (`klanten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_adressen_bestelling`
    FOREIGN KEY (`FK_adressen_bestelling` , `FK_adressen_type` , `FK_klanten_id`)
    REFERENCES `mydb`.`adressen` (`adressen_id` , `adresssen_type` , `FK_klanten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bestellingregels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bestellingregels` (
  `bestellingregels_id` INT NOT NULL,
  `bestellingen_id` INT NOT NULL,
  `hoeveelheid` INT NULL,
  INDEX `idBestelling_idx` (`bestellingen_id` ASC),
  PRIMARY KEY (`bestellingregels_id`),
  CONSTRAINT `FK_producten_id`
    FOREIGN KEY (`bestellingregels_id`)
    REFERENCES `mydb`.`producten` (`producten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_bestellingen_id`
    FOREIGN KEY (`bestellingen_id`)
    REFERENCES `mydb`.`bestellingen` (`bestellingen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturen` (
  `facturen_id` INT NOT NULL AUTO_INCREMENT,
  `FK_bestellingen_id` INT NOT NULL,
  `FK_klanten_id` INT NULL,
  `FK_adressen_factuur` INT NULL,
  `FK_adressen_type` INT NULL,
  `totaalprijs` DECIMAL NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Nog_niet_betaald',
  PRIMARY KEY (`facturen_id`, `FK_bestellingen_id`),
  INDEX `fk_Betaling_Bestelling1_idx` (`FK_bestellingen_id` ASC),
  INDEX `FK_adressen_factuur_idx` (`FK_adressen_factuur` ASC, `FK_adressen_type` ASC, `FK_klanten_id` ASC),
  INDEX `FK_klanten_id_idx` (`FK_klanten_id` ASC),
  CONSTRAINT `FK_factuur_bestellingen_id`
    FOREIGN KEY (`FK_bestellingen_id`)
    REFERENCES `mydb`.`bestellingen` (`bestellingen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_adressen_factuur`
    FOREIGN KEY (`FK_adressen_factuur` , `FK_adressen_type` , `FK_klanten_id`)
    REFERENCES `mydb`.`adressen` (`adressen_id` , `adresssen_type` , `FK_klanten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_factuur_klanten_id`
    FOREIGN KEY (`FK_klanten_id`)
    REFERENCES `mydb`.`klanten` (`klanten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
