-- MySQL Script generated by MySQL Workbench
-- Thu 12 Jan 2017 02:52:09 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medewerker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medewerker` (
  `idMedewerker` INT NOT NULL AUTO_INCREMENT,
  `idAdmin` INT NOT NULL,
  `wachtwoord` VARCHAR(45) NULL,
  `status` INT NULL,
  `e-mail` VARCHAR(45) NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedewerker`),
  INDEX `fk_Medewerker_Medewerker1_idx` (`idAdmin` ASC),
  CONSTRAINT `fk_Medewerker_Medewerker1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `mydb`.`Medewerker` (`idMedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klant` (
  `idKlant` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `telefoonnummer` INT NULL,
  `BezorgHuisnummer` INT NULL,
  `BezorgHuisnummerToegvoeging` VARCHAR(45) NULL,
  `BezorgPostcode` VARCHAR(45) NULL,
  `FactuurPostcode` VARCHAR(45) NULL,
  `FactuurHuisnummer` INT NULL,
  `FactuurHuisnummerToevoeging` VARCHAR(45) NULL,
  `Land` VARCHAR(45) NULL,
  `Medewerker_idMedewerker` INT NOT NULL,
  PRIMARY KEY (`idKlant`),
  INDEX `fk_Klant_Medewerker1_idx` (`Medewerker_idMedewerker` ASC),
  CONSTRAINT `fk_Klant_Medewerker1`
    FOREIGN KEY (`Medewerker_idMedewerker`)
    REFERENCES `mydb`.`Medewerker` (`idMedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kaas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kaas` (
  `idKaas` INT NULL,
  `omschrijving` VARCHAR(45) NULL,
  `soort` VARCHAR(45) NULL,
  `prijs` DOUBLE NULL,
  `voorraad` INT NULL,
  `aantal` INT NULL,
  `prijstotaal` DOUBLE NULL,
  `Medewerker_idMedewerker` INT NOT NULL,
  PRIMARY KEY (`idKaas`),
  INDEX `fk_Kaas_Medewerker1_idx` (`Medewerker_idMedewerker` ASC),
  CONSTRAINT `fk_Kaas_Medewerker1`
    FOREIGN KEY (`Medewerker_idMedewerker`)
    REFERENCES `mydb`.`Medewerker` (`idMedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Betaling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Betaling` (
  `idBetaling` INT NOT NULL AUTO_INCREMENT,
  `idKlant` INT NOT NULL,
  `totaalprijs` FLOAT NULL,
  `status` VARCHAR(45) NULL,
  `Medewerker_idMedewerker` INT NOT NULL,
  PRIMARY KEY (`idBetaling`, `idKlant`),
  INDEX `fk_Betaling_Klant1_idx` (`idKlant` ASC),
  INDEX `fk_Betaling_Medewerker1_idx` (`Medewerker_idMedewerker` ASC),
  CONSTRAINT `fk_Betaling_Klant1`
    FOREIGN KEY (`idKlant`)
    REFERENCES `mydb`.`Klant` (`idKlant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Betaling_Medewerker1`
    FOREIGN KEY (`Medewerker_idMedewerker`)
    REFERENCES `mydb`.`Medewerker` (`idMedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bestelling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bestelling` (
  `idBestelling` INT NOT NULL AUTO_INCREMENT,
  `idKlant` INT NOT NULL,
  `aantal_artikelen` INT NULL,
  `totaalprijs` DOUBLE NULL,
  `Betaling_idBetaling` INT NULL,
  `Medewerker_idMedewerker` INT NOT NULL,
  PRIMARY KEY (`idBestelling`, `idKlant`),
  INDEX `fk_Winkelwagen_Betaling1_idx` (`Betaling_idBetaling` ASC),
  INDEX `fk_Winkelwagen_Medewerker1_idx` (`Medewerker_idMedewerker` ASC),
  CONSTRAINT `fk_Winkelwagen_Betaling1`
    FOREIGN KEY (`Betaling_idBetaling`)
    REFERENCES `mydb`.`Betaling` (`idBetaling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Winkelwagen_Medewerker1`
    FOREIGN KEY (`Medewerker_idMedewerker`)
    REFERENCES `mydb`.`Medewerker` (`idMedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bestellingtoestand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bestellingtoestand` (
  `idBestellingtoestand` INT NOT NULL,
  `idWinkelwagen` INT NULL DEFAULT CURRENT_TIMESTAMP,
  `toestand` INT NULL,
  `datumvanbehandeling` DATE NULL,
  INDEX `idWinkelwagen_idx` (`idWinkelwagen` ASC),
  PRIMARY KEY (`idBestellingtoestand`),
  CONSTRAINT `idWinkelwagen`
    FOREIGN KEY (`idWinkelwagen`)
    REFERENCES `mydb`.`Bestelling` (`idBestelling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Details_bestelling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Details_bestelling` (
  `idKaas` INT NOT NULL,
  `idWinkelwagen` INT NOT NULL,
  `hoeveelheid` INT NULL,
  PRIMARY KEY (`idKaas`, `idWinkelwagen`),
  INDEX `idKaas_idx` (`idKaas` ASC),
  INDEX `idWinkelwagen_idx` (`idWinkelwagen` ASC),
  CONSTRAINT `idKaas`
    FOREIGN KEY (`idKaas`)
    REFERENCES `mydb`.`Kaas` (`idKaas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idWinkelwagen`
    FOREIGN KEY (`idWinkelwagen`)
    REFERENCES `mydb`.`Bestelling` (`idBestelling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aankoop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aankoop` (
  `idAankoop` INT NOT NULL,
  `Betaling_idBetaling` INT NOT NULL,
  PRIMARY KEY (`idAankoop`),
  INDEX `fk_Aankoop_Betaling1_idx` (`Betaling_idBetaling` ASC),
  CONSTRAINT `fk_Aankoop_Betaling1`
    FOREIGN KEY (`Betaling_idBetaling`)
    REFERENCES `mydb`.`Betaling` (`idBetaling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aankoop_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aankoop_details` (
  `idAankoop_details` INT NOT NULL,
  `Kaas_idKaas` INT NOT NULL,
  `Aankoop_idAankoop` INT NOT NULL,
  PRIMARY KEY (`idAankoop_details`),
  INDEX `fk_Aankoop_details_Kaas1_idx` (`Kaas_idKaas` ASC),
  INDEX `fk_Aankoop_details_Aankoop1_idx` (`Aankoop_idAankoop` ASC),
  CONSTRAINT `fk_Aankoop_details_Kaas1`
    FOREIGN KEY (`Kaas_idKaas`)
    REFERENCES `mydb`.`Kaas` (`idKaas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aankoop_details_Aankoop1`
    FOREIGN KEY (`Aankoop_idAankoop`)
    REFERENCES `mydb`.`Aankoop` (`idAankoop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'klant';

GRANT SELECT ON TABLE `mydb`.* TO 'klant';
CREATE USER 'medewerker';

GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'medewerker';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'medewerker';
GRANT SELECT ON TABLE `mydb`.* TO 'medewerker';
CREATE USER 'admin';

GRANT ALL ON `mydb`.* TO 'admin';
GRANT ALL ON TABLE `mydb`.`Klant` TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
